spring.application.name=ClientifyApi
spring.datasource.url=jdbc:postgresql://ep-broad-shape-ap4pv2cr-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_UIY9Oh1fskPG&sslmode=require&channelBinding=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=ERROR
server.forward-headers-strategy=framework

jwt.secret=uoAYayOj9X8t/oBBnwU+WVBext6OImG1h1UQE+d0d0E=
jwt.expiration-ms=3600000